name: Push Coder Template

on:
  push:
    branches:
        - main

jobs:
    find-changes:
      runs-on: ubuntu-latest
      outputs:
        dirs: ${{ steps.set-matrix.outputs.matrix }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Find changed directories
          id: changed-directories
          uses: tj-actions/changed-files@v40
          with:
            json: true
            dir_names: true
            files_ignore: .*/**\n.**

        - name: Set matrix
          id: set-matrix
          run: echo "matrix={\"dirs\":${{ steps.changed-directories.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

    update:
      runs-on: ubuntu-latest
      needs:
        - find-changes
      strategy:
        matrix: ${{  fromJson(needs.find-changes.outputs.dirs)  }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Get latest commit hash
          id: latest_commit
          run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

        - name: Get commit title
          id: commit_title
          run: echo "title=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

        - name: Update Coder Template
          uses: matifali/update-coder-template@v3
          with:
            id: ${{ toJson(matrix.dirs) }}
            dir: ${{ toJson(matrix.dirs) }}
            url: https://coder.ivanlau.dev
            name: ${{ steps.latest_commit.outputs.hash }}
            message: ${{ steps.commit_title.outputs.title }}
            coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}
